name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout ${{ github.event.repository.name }} repository # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node ${{ matrix.node-version }}  # Install Node, so we can build the project
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # Cache installed project dependencies
      - name: Install project dependencies
        run: yarn
      - name: Run typechecking
        run: yarn tsc --noEmit --pretty
      - name: Run linting
        run: yarn eslint --ext js,jsx,ts,tsx src
      - name: Run style linting
        run: yarn stylelint **/*.{css,scss}
      - name: Run tests
        run: yarn test
      - name: Build app
        run: yarn build

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout ${{ github.event.repository.name }} repository
        uses: actions/checkout@v3
      - name: Trigger Netlify build
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_RELEASE_BUILD_HOOK_ID }}
      - name: Create release notes
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}